Repository google/accompanist, pull requests merged in 2020-09, with the labels that each got.

#71 Update to Compose 1.0.0-alpha02
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  gradle.properties
Labels: automerge, cla: yes

#74 Updating snapshot to main
  README.md
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#73 Snapshot 6824694
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  sample/src/main/java/dev/chrisbanes/accompanist/sample/SampleApplication.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilLazyColumnSample.kt
Labels: automerge, cla: yes

#78 Compile against SDK 30
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  sample/build.gradle
  sample/src/main/java/dev/chrisbanes/accompanist/sample/MainActivity.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/SampleApplication.kt
Labels: automerge, cla: yes

#80 Add `ImageLoader` parameter
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/api/coil.api
  coil/build.gradle
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
Labels: automerge, cla: yes

#81 New version: v0.2.2
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
  gradle.properties
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilLazyColumnSample.kt
Labels: cla: no

#82 Improve Gradle caching in Actions
  .github/workflows/build.yml
Labels: cla: yes

#83 Bump snapshot version to Compose 6834837 build
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  gradle.properties
Labels: automerge, cla: yes

#85 Update to Compose SNAPSHOT 6838769
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  gradle.properties
Labels: cla: yes

#87 Add doc to help maintainers update this library
  build.gradle
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  deploy_docs.sh
  docs/updating.md
  docs/using-snapshot-version.md
  gradle.properties
  mkdocs.yml
Labels: cla: yes

#88 API updates
  coil/api/coil.api
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
Labels: cla: yes

#90 Use Dokka 1.4.0
  build.gradle
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/build.gradle
  generate_docs.sh
Labels: cla: yes

#91 Update to Coil 1.0.0-rc2
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
Labels: cla: yes

#89 Refactor crossfade APIs
  coil/README.md
  coil/api/coil.api
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt
Labels: cla: yes

#94 Update to Compose SNAPSHOT 6854728
  build.gradle
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/build.gradle
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
  sample/build.gradle
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt
Labels: cla: yes

#93 More API changes
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/api/coil.api
  coil/build.gradle
  coil/src/androidTest/AndroidManifest.xml
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTestApplication.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/RequestActor.kt
Labels: cla: yes

#95 Update to Coil 1.0.0-rc3
  build.gradle
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
Labels: cla: yes

#97 Update to snapshot 6860046
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
Labels: automerge, cla: yes

#101 Update README.md
  coil/README.md
Labels: cla: yes

#103 Doc fixes
  .gitignore
  coil/README.md
  generate_docs.sh
  mkdocs.yml
  picasso/README.md
Labels: cla: yes

#104 Try fixing flakey `PicassoTest.loading_slot`
  picasso/src/androidTest/java/dev/chrisbanes/accompanist/picasso/PicassoTest.kt
Labels: cla: yes
