Repository google/accompanist, pull requests merged in 2020-08, with the labels that each got.

#57 Update to Compose snapshot 6745209
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Modifier.kt
  gradle.properties
Labels: cla: yes

#58 Try out probot-auto-merge
  .github/auto-merge.yml
Labels: automerge, cla: yes

#59 Update to Compose snapshot #6752477
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  gradle.properties
Labels: automerge, cla: yes

#60 Update to Compose snapshot 6759487
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  gradle.properties
Labels: automerge, cla: yes

#61 Fix using CoilImage with an implicit size
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/Assertions.kt
  coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Modifier.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt
Labels: automerge, cla: yes

#62 Upgrade to Kotlin 1.4.0
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
Labels: cla: yes

#65 Remove MDC library
  README.md
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  mdc-theme/README.md
  mdc-theme/build.gradle
  mdc-theme/gradle.properties
  mdc-theme/src/androidTest/AndroidManifest.xml
  mdc-theme/src/androidTest/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeTest.kt
  mdc-theme/src/androidTest/java/dev/chrisbanes/accompanist/mdctheme/MdcActivity.kt
  mdc-theme/src/androidTest/java/dev/chrisbanes/accompanist/mdctheme/NotMaterialThemeTest.kt
  mdc-theme/src/androidTest/java/dev/chrisbanes/accompanist/mdctheme/NotMdcActivity.kt
  mdc-theme/src/androidTest/res/font/rubik_300.ttf
  mdc-theme/src/androidTest/res/font/rubik_400.ttf
  mdc-theme/src/androidTest/res/font/rubik_500.ttf
  mdc-theme/src/androidTest/res/font/rubik_700.ttf
  mdc-theme/src/androidTest/res/values/styles.xml
  mdc-theme/src/androidTest/res/values/test_colors.xml
  mdc-theme/src/androidTest/res/values/themes.xml
  mdc-theme/src/androidTest/res/values/type.xml
  mdc-theme/src/main/AndroidManifest.xml
  mdc-theme/src/main/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeFromMdcTheme.kt
  mdc-theme/src/main/res/values/theme_attrs.xml
  sample/build.gradle
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilGridSample.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilLazyColumnSample.kt
  sample/src/main/java/dev/chrisbanes/accompanist/sample/mdc/MdcSampleActivity.kt
  sample/src/main/res/values/colors.xml
  sample/src/main/res/values/shape.xml
  sample/src/main/res/values/strings.xml
  sample/src/main/res/values/themes.xml
  settings.gradle
Labels: cla: yes

#64 Update to Coil v1.0.0-rc1
  build.gradle
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
Labels: cla: yes

#67 v0.2.0!
  buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: no

#68 Fix grammatical errors
  README.md
Labels: automerge, cla: yes
